from flask import Flask
from flask_cors import CORS
from routes import setup_routes  

app = Flask(__name__)
CORS(app) #Cross-Origin Resource Sharing(CORS) allows your Flask app to handle requests from different origins.

setup_routes(app) # Hooks all API endpoints

if __name__ == '__main__':
    app.run(debug=True)
    
# Running the app launches the server, which listens for incoming HTTP requests and serves responses based on your routes and business logic.


    
# .vscode stores workspace settings for the project and settings.json contains configurations for the editor.
# venv is a virtual environment directory that contains the Python interpreter and installed packages for this project.
# requirements.txt lists the Python packages required for the project.
# _pypycache_ contains autogenerated .pyc complied files to speed up execution.
# _init_.py is an empty file that indicates that the directory should be treated as a Python package.



